// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqq5eBWUyIjOZyMBLzFcEKJTTJtL9FBY',
    appId: '1:661582602052:web:4c4a1345acc1fcdae9c111',
    messagingSenderId: '661582602052',
    projectId: 'flutter-firebase-6cf6d',
    authDomain: 'flutter-firebase-6cf6d.firebaseapp.com',
    storageBucket: 'flutter-firebase-6cf6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlOiUOeHZwfluUMneCwby9vOj1zjUSMKM',
    appId: '1:661582602052:android:d969ea3608486b9de9c111',
    messagingSenderId: '661582602052',
    projectId: 'flutter-firebase-6cf6d',
    storageBucket: 'flutter-firebase-6cf6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgaOG85jPVZ6Ineb1WSe70EtbRWA4sKOI',
    appId: '1:661582602052:ios:252b611c894cff9be9c111',
    messagingSenderId: '661582602052',
    projectId: 'flutter-firebase-6cf6d',
    storageBucket: 'flutter-firebase-6cf6d.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgaOG85jPVZ6Ineb1WSe70EtbRWA4sKOI',
    appId: '1:661582602052:ios:252b611c894cff9be9c111',
    messagingSenderId: '661582602052',
    projectId: 'flutter-firebase-6cf6d',
    storageBucket: 'flutter-firebase-6cf6d.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqq5eBWUyIjOZyMBLzFcEKJTTJtL9FBY',
    appId: '1:661582602052:web:5a5c622b945949a4e9c111',
    messagingSenderId: '661582602052',
    projectId: 'flutter-firebase-6cf6d',
    authDomain: 'flutter-firebase-6cf6d.firebaseapp.com',
    storageBucket: 'flutter-firebase-6cf6d.appspot.com',
  );
}
